version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: blogram-frontend-docker

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: blogram-backend-docker

  db:
    image: postgres:alpine
    container_name: db
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:

volumes:
  postgres-data: