version: '3.8'
services:
  app:
    build:
    container_name: blogram-docker

  db:
    image: postgres:alpine
    container_name: db
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:

volumes:
  postgres-data: