name = "backend"
main = "src/index.ts"
compatibility_date = "2024-12-04"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYTg0NmUwZDMtNDI1YS00MGIyLWExN2YtYTkyODQ5MTBmYmU1IiwidGVuYW50X2lkIjoiNDczMDA5NGRlY2UyOGRjODg1ZTIwODBkYjFmZTYxOTJlNzAyYjZjNDk2NzYyYzg2NTk5ZWQ2MjkwZDMxZTg3NiIsImludGVybmFsX3NlY3JldCI6IjhlZmE1OWI1LTFkNTQtNDVjMi1iZDIzLWViMjllM2ZiYzFlMyJ9.lYA6BO88nMVMQvTXXtkR6hW6E-qVn4_UEVqh_PO1TJg"

